### ISSUE TITLE
How much is the required GPU memory at least? 

### ISSUE THREAD

**Issue by yangyu12** [autonomousvision/graf#6]
Hi, thanks for releasing the codes. It is really interesting work. I am trying to train a model from scratch on CUB dataset. After finishing the preparation, I run the following command
`CUDA_VISIBLE_DEVICES=0 python train.py configs/cub.yaml` 
using single GPU. However, After this log
`[cub_64 epoch 7, it 7990, t 1.099] g_loss = 1.0365, d_loss = 1.1345, reg=0.0230`,
I got 
`RuntimeError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 11.91 GiB total capacity; 10.89 GiB already allocated; 1.06 MiB free; 11.29 GiB reserved in total by PyTorch)`

I am using TITAN X (Pascal) with 12196MiB available memory. I wonder how much is the minimum GPU  memory that can run the training. Or do you have any instructions for adjusting hyperparameters to decrease memory consumption? 

Thanks!

**Comment by yangyu12** [comment]
Update: I notice that the memory consumption increases incrementally by 2MiB, starting from around 8400MiB. Is there any memory leak in the program?

**Comment by yangyu12** [comment]
Sorry, it is an issue with my environment. I created an environment using the `environment.yaml` you provided and ran training but encountered the above problems. Now I switch to my native environment with which I do not observe the above problem. Thus this issue can be closed.

**Comment by ventusff** [comment]
> Update: I notice that the memory consumption increases incrementally by 2MiB, starting from around 8400MiB. Is there any memory leak in the program?

@yangyu12 Hi, sorry for bothering, but can you tell me what's the significant difference between your native environment and `environment.yaml` in this repo? 
I've still encountered the same memory leaking problem, with gpu consumption increases 2MiB every iteration, in my own native environment. 

I'm using pytorch==1.7.1 and cuda11.0.

Besides, I noticed that the precise location which causes the gpu memory leaking problem is at: 
https://github.com/autonomousvision/graf/blob/b6d72178e11d6e4d8fcb4db824c3b1cda4b8c6c4/submodules/GAN_stability/gan_training/train.py#L69

And I'm still trying to debug this issue.

**Comment by ventusff** [comment]
Update: I found the cause of GPU memory leak in my case when running with torch==1.7.1.

It's because I'm running with `torch.set_detect_anomaly(True)`, which I found will cause a memory leak along with `torch.autograd.grad()`.

It seems to be a problem with pytorch itself, so I've submitted an [issue](https://github.com/pytorch/pytorch/issues/51349) in pytorch repo.

**Comment by yangyu12** [comment]
Hi @ventusff ,
   Sorry for the late response. In my native environment, I am using pytorch==1.6.0 and cuda10.1.
   As for the location where memory leaking happens, I have the same finding as you. However, it does not cause any problems with pytorch==1.6.0.
   Thanks for the information about why this memory leak happens. However, I can not find in this source code where `torch.set_detect_anomaly(True)` is set. Could you please locate it for me?  Thank you!

**Comment by ventusff** [comment]
Hi @yangyu12 
It's in 
https://github.com/autonomousvision/graf/blob/b6d72178e11d6e4d8fcb4db824c3b1cda4b8c6c4/submodules/nerf_pytorch/run_nerf_helpers_mod.py#L2

Just a reminder, for every imported python files, any line outside function/class definitions etc. will be executed. So once `run_nerf_helpers_mod.py` is imported, this line inside it `torch.autograd.set_detect_anomaly(True)` will be executed.

Besides, since it's a known reproducible issue, maybe you could reopen this issue? or we can pull a PR to this repo.

**For anyone who encouters this memory leaking problem, just comment out the above line, then enjoy training :)**

**Comment by ventusff** [comment]
As for pytorch versions, I think the memory leaking problem is introduced sometime after `torch==1.7.0` or earlier. 

I have tested with `torch==1.7.0`, `torch==1.7.1`, `torch==1.8.0dev`, and the latest pytorch `master` branch, all encountered the same memory leaking problem when using `torch.autograd.grad()` with `torch.autograd.set_detect_anomaly(True)`.

**Comment by yangyu12** [comment]
Hi @ventusff ,
   Thanks for pointing it out. This issue has been reopened. Feel free to draw author's attention here.

**Comment by katjaschwarz** [comment]
Hi,

this is super interesting, thanks for analyzing this issue!
I commented out line 2 as you suggested - now there should be no more memory leakage.

**Comment by ventusff** [comment]
Cool, thanks :) 

Besides, after this issue was submitted to pytorch, it has been fixed with surprising efficiency just within these few days.
So there will be no problem using these two functions at the same time in future pytorch versions.

See [pytorch/issue#51349](https://github.com/pytorch/pytorch/issues/51349) and [pytorch-commit](https://github.com/pytorch/pytorch/commit/2e8e560cdf003cfb3f17523bb68fdd642fece082)
